### ISSUE TITLE
Failed to load the tool-bar package

### ISSUE THREAD

**Issue by Frinkiac-7** [suda/tool-bar#322] opened 2020-10-15 13:16 UTC
[Enter steps to reproduce:]

1. Clicked on the "1 Update" notification in the lower right of Atom
2. Toolbar installed and now generates this error every time.

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [tool-bar](https://github.com/suda/toolbar) package 1.4.0

### Stack Trace

Failed to load the tool-bar package

```
At '../dist/iconsets.css' wasn't found. Tried - C:\Users\garciar\.atom\packages\tool-bar\dist\iconsets.css,C:\Users\garciar\AppData\Local\atom\app-1.52.0\resources\app.asar\node_modules\one-dark-syntax\dist\iconsets.css,C:\Users\garciar\AppData\Local\atom\app-1.52.0\resources\app.asar\node_modules\atom-dark-ui\dist\iconsets.css,C:\Users\garciar\AppData\Local\atom\app-1.52.0\resources\app.asar\static\dist\iconsets.css,C:\Users\garciar\AppData\Local\atom\app-1.52.0\resources\app.asar\dist\iconsets.css,..\dist\iconsets.css in C:\Users\garciar\.atom\packages\tool-bar\styles\tool-bar.less:2:0

LessError: '../dist/iconsets.css' wasn't found. Tried - C:\Users\garciar\.atom\packages\tool-bar\dist\iconsets.css,C:\Users\garciar\AppData\Local\atom\app-1.52.0\resources\app.asar\node_modules\one-dark-syntax\dist\iconsets.css,C:\Users\garciar\AppData\Local\atom\app-1.52.0\resources\app.asar\node_modules\atom-dark-ui\dist\iconsets.css,C:\Users\garciar\AppData\Local\atom\app-1.52.0\resources\app.asar\static\dist\iconsets.css,C:\Users\garciar\AppData\Local\atom\app-1.52.0\resources\app.asar\dist\iconsets.css,..\dist\iconsets.css
at C:\Users\garciar\.atom\packages\tool-bar\styles\tool-bar.less:2:0
```

### Commands

```
```

### Non-Core Packages

```
atom-file-icons 0.7.1 
tool-bar 1.4.0 
```

**Comment by suda** [comment] 2020-10-15 13:30
Closing this in as it's a duplicate of #314

**Closed by suda** 2020-10-15 13:30 UTC
