### ISSUE TITLE
Show over/under Tree View as well

### ISSUE THREAD

**Issue by pradyunsg** [suda/tool-bar#91] opened 2015-09-22 13:02 UTC
Currently, the Tool Bar is shown only over/under the editor-portion of the editor.

It would be nicer if it would be shown over and under the tree-view as well (File Browser/Sidebar/whatever).

PS: I was planning to use this as an alternative to the menu-bar but without something this, it's not really good-looking. :sweat_smile:

**Comment by jerone** [comment] 2015-09-22 18:16
> It would be nicer if it would be shown over and under the tree-view as well

That's not possible due to Atom's way of available panels in the workspace. See https://discuss.atom.io/t/rearrange-status-bar-to-the-bottom-panel/18597/6

The linked topic does note a workaround that you can put in your `styles.less` to achieve the same effect.

**Comment by pradyunsg** [comment] 2015-09-23 01:35
Ah, so it's technically difficult. So, could you put the relevant code snippet in the README (for reference?)

PS: I did this but I'm having a hard time figuring out the height part...

**Comment by jerone** [comment] 2015-09-26 09:00
Tracking upstream: https://github.com/atom/atom/issues/8939

**Comment by simurai** [comment] 2015-10-03 02:00
FYI: I tried out putting the tool-bar full width at the bottom https://github.com/atom/atom/issues/8939#issuecomment-145192628, but it felt weird. I think the status-bar should always be the last thing at the bottom and packages can be above it.

Also, having the tool-bar at the top with full-width would make it visually uneven. So I think keeping it like it is now is still the best option. Personally, I prefer the tool-bar on the sides.

**Comment by jerone** [comment] 2015-10-03 08:58
Personally I have the tool-bar positioned at the top, like any other (Windows) desktop program has placed their (customizable) toolbars. To this day I find it weird that it's beside the tree-view and not above it, while it contains buttons that are related to the tree-view and not the editor only.
I still believe [this](https://github.com/atom/atom/issues/8939) should be implemented as another API function, so packages can position their bars/panels like they want.

**Comment by jerone** [comment] 2016-02-01 21:25
https://github.com/atom/atom/pull/9274 was just merged, making it possible to attach to a panel that spans across the whole width and not just above/under the editor.

Waiting for another beta release before we can work on this.

**Comment by simurai** [comment] 2016-02-01 23:55
> Waiting for another beta release before we can work on this.

Something I was wondering.. how do you add something to beta but not stable? Do you release tool-bar with something like `"atom": ">=1.5.0"` [here](https://github.com/suda/tool-bar/blob/master/package.json#L14). Then only people with that version should see an update. And then once it lands in stable, go back to `"atom": ">=0.188.0"`? I guess the problem is that it would block any other updates to tool-bar that should go into stable?

**Comment by jerone** [comment] 2016-02-02 10:58
> how do you add something to beta but not stable?

I don't think this is possible yet, as it looks like the `engine` property [is ignored](https://github.com/atom/atom/issues/3741) at this time.

For now I just want to wait for beta to have the updated core packages required for this feature.

**Closed** 2016-03-18 18:23 UTC
Labels: enhancement, upstream

**Comment by pradyunsg** [comment] 2016-03-18 18:46
:sparkles: Yay! :tada:

**Comment by varemenos** [comment] 2017-04-14 11:14
A Docks feature was added recently to the latest beta, I'm ynder the assumption that this feature could be implemented via the Docks API.
