### ISSUE TITLE
Add support for secondary toolbar? 

### ISSUE THREAD

**Issue by JamesCoyle** [suda/tool-bar#174] opened 2016-10-30 16:01 UTC
Would it be at all possible for this project to support a secondary toolbar? I have the toolbar full of basic atom functions but after installing PlatformIO the toolbar gets filled so you have to scroll which means icons are never where expected. It would be nice if there was a way to shift the PlatformIO icons over to their own toolbar.

**Comment by jerone** [comment] 2016-10-30 18:30
Duplicate of https://github.com/suda/tool-bar/issues/80

To answer your question. No, it's not (yet) possible to have multiple tool-bars. On the vertical tool-bar the overflow of buttons creates a scrollbar. The horizontal tool-bar however, overflows the buttons into a new row of buttons (simulating two tool-bars).

**Closed by jerone** 2016-10-30 18:30 UTC
Labels: duplicate
