### ISSUE TITLE
Failed to load the tool-bar package

### ISSUE THREAD

**Issue by definama** [suda/tool-bar#319] opened 2020-10-15 12:27 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0-nightly3 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [tool-bar](https://github.com/suda/toolbar) package 1.4.0

### Stack Trace

Failed to load the tool-bar package

```
At '../dist/iconsets.css' wasn't found. Tried - C:\Users\defina\.atom\packages\tool-bar\dist\iconsets.css,C:\Users\defina\.atom\packages\base16-tomorrow-dark-theme-vivid\dist\iconsets.css,C:\Users\defina\AppData\Local\atom-nightly\app-1.54.0-nightly3\resources\app.asar\node_modules\atom-dark-ui\dist\iconsets.css,C:\Users\defina\AppData\Local\atom-nightly\app-1.54.0-nightly3\resources\app.asar\static\dist\iconsets.css,C:\Users\defina\AppData\Local\atom-nightly\app-1.54.0-nightly3\resources\app.asar\dist\iconsets.css,..\dist\iconsets.css in C:\Users\defina\.atom\packages\tool-bar\styles\tool-bar.less:2:0

LessError: '../dist/iconsets.css' wasn't found. Tried - C:\Users\defina\.atom\packages\tool-bar\dist\iconsets.css,C:\Users\defina\.atom\packages\base16-tomorrow-dark-theme-vivid\dist\iconsets.css,C:\Users\defina\AppData\Local\atom-nightly\app-1.54.0-nightly3\resources\app.asar\node_modules\atom-dark-ui\dist\iconsets.css,C:\Users\defina\AppData\Local\atom-nightly\app-1.54.0-nightly3\resources\app.asar\static\dist\iconsets.css,C:\Users\defina\AppData\Local\atom-nightly\app-1.54.0-nightly3\resources\app.asar\dist\iconsets.css,..\dist\iconsets.css
at C:\Users\defina\.atom\packages\tool-bar\styles\tool-bar.less:2:0
```

### Commands

```
```

### Non-Core Packages

```
ascii-hex 0.2.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
base16-tomorrow-dark-theme-vivid 3.0.0 
chrome-color-picker 0.8.0 
column-select 1.0.1 
copy-highlighted 0.5.0 
Delete-Whitelines 0.6.4 
duplicate-removal 0.1.3 
filter-lines 2.0.0 
flex-tool-bar 2.2.1 
highlight-selected 0.17.0 
html-tag-auto-complete 2.0.0 
isotope-ui 2.8.5 
language-batchfile 0.7.5 
language-dashtcl 1.9.1 
language-log 1.10.1 
language-powershell 5.0.0 
lines 0.13.1 
metro-syntax 0.3.1 
metro-ui 2.2.2 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
multi-cursor 3.0.0 
pigments 0.40.6 
pretty-html 1.0.0 
process-palette 0.17.0 
project-folder 1.5.0 
scroll-sync 0.2.4 
seti-ui 1.11.0 
split-diff 1.6.1 
Sublime-Style-Column-Selection 1.7.5 
sublime-ui-dark 0.0.7 
sync-settings 5.0.5 
sync-settings-folder-location 1.0.13 
title-bar-replacer 1.8.3 
todo-show 2.3.2 
tool-bar 1.4.0 
tree-view-filter 0.5.5 
viscode-ui 0.3.1 
xml-formatter 0.13.0 
```

**Comment by suda** [comment] 2020-10-15 13:29
Closing this in as it's a duplicate of #314

**Closed by suda** 2020-10-15 13:29 UTC
