### ISSUE TITLE
"@button-text-color-selected is undefined"

### ISSUE THREAD

**Issue by xieve** [suda/tool-bar#224] opened 2018-02-11 14:07 UTC
I just updated the package from inside Atom, restarted it, and this error popped up. I guess it's got something to do with the theme as in #219.

**Atom**: 1.23.3 x64
**Electron**: 1.7.12
**OS**: linux 4.15.1-2-ARCH
**Thrown From**: [tool-bar](ssh://git@github.com/suda/toolbar) package 1.1.5

### Themes
| UI | Syntax |
| --- | --- |
| apex-muted-ui 0.1.4 | ariake-dark-syntax 0.1.3 |

### Stack Trace

Failed to load the tool-bar package

```
At variable @button-text-color-selected is undefined in /home/xieve/.atom/packages/tool-bar/styles/tool-bar.less:37:13

LessError: variable @button-text-color-selected is undefined
  at /packages/tool-bar/styles/tool-bar.less:37:13
```

### Non-Core Packages

```
apex-muted-ui 0.1.4 
ariake-dark-syntax 0.1.3 
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.16 
git-plus 7.10.0 
gpp-compiler 3.0.7 
intentions 1.1.5 
language-ini 1.19.0 
language-lua 0.9.11 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-linter 2.1.3 
platformio-ide 2.0.1 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.0 
tool-bar 1.1.5 
```

**Comment by suda** [comment] 2018-02-11 17:11
Duplicate of https://github.com/suda/tool-bar/issues/219. Fixed in 1.1.6

**Closed by suda** 2018-02-11 17:11 UTC
