### ISSUE TITLE
Uncaught Error: Cannot call function 'setTouchBar' on missing remote object 87Error: Cannot call...

### ISSUE THREAD

**Issue by newelement** [suda/tool-bar#256] opened 2019-03-12 14:56 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [tool-bar](https://github.com/suda/toolbar) package 1.1.11

### Stack Trace

Uncaught Error: Cannot call function 'setTouchBar' on missing remote object 87
Error: Cannot call function 'setTouchBar' on missing remote object 87
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:221

Error: Cannot call function 'setTouchBar' on missing remote object 87
Error: Cannot call function 'setTouchBar' on missing remote object 87
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:125:16)
    at TouchBarManager._setTouchBar (/packages/tool-bar/lib/touch-bar-manager.js:86:29)
    at _updateDebounce.setTimeout (/packages/tool-bar/lib/touch-bar-manager.js:38:50)
```

### Commands

```
     -1:04.4.0 project-viewer:createNewProject (div.list-item)
     -0:12.7.0 tree-view:duplicate (span.name.icon.gear-icon.dark-green)
     -0:11.9.0 core:move-right (input.hidden-input)
  8x -0:11.6.0 core:backspace (input.hidden-input)
     -0:10.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.4 
atom-ide-ui 0.13.0 
file-icons 2.1.30 
flex-tool-bar 2.1.2 
git-time-machine 2.1.0 
ide-css 0.3.2 
ide-html 0.5.0 
ide-php 0.7.18 
ide-typescript 0.8.0 
ide-vue 0.1.9 
language-vue 0.24.0 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
pigments 0.40.2 
platformio-ide-terminal 2.9.1 
project-manager 3.3.6 
project-viewer 1.3.1 
remote-ftp 2.2.2 
split-diff 1.6.0 
sync-settings 0.8.6 
tag 0.5.0 
teletype 0.13.3 
tool-bar 1.1.11 
```

**Comment by suda** [comment] 2019-05-09 11:56
I believe this might be a duplicate of #252.

**Closed by suda** 2019-05-09 11:56 UTC
Labels: duplicate
